<a href="https://colab.research.google.com/github/rayasrujanareddy/ML-3/blob/main/Feature_Engineering_Preprocessing_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Feature Engineering/Preprocessing assignment



## Question 1-
## Finding mean and variance of the elements

In [ ]:
import numpy as np

# Create a 1xN dimensional array (N-dimensional feature vector)
N = 10  # Example dimension size
feature_vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Compute the mean of the elements in the array
mean = np.mean(feature_vector)

# Compute the variance of the elements in the array
variance = np.var(feature_vector, ddof=1)  # Sample variance (ddof=1)

# Output the results
print(f"Feature Vector: {feature_vector}")
print(f"Mean: {mean}")
print(f"Variance: {variance}")


Feature Vector: [ 1  2  3  4  5  6  7  8  9 10]
Mean: 5.5
Variance: 9.166666666666666


## Question 2 -
## Covariance between two vectors

In [ ]:
# Define two 1xM dimensional arrays (N-dimensional feature vectors)
vector_x = [1, 2, 3, 4, 5]
vector_y = [5, 4, 3, 2, 1]

# Calculate the mean of both vectors
mean_x = sum(vector_x) / len(vector_x)
mean_y = sum(vector_y) / len(vector_y)

# Calculate the covariance
covariance = sum((vector_x[i] - mean_x) * (vector_y[i] - mean_y) for i in range(len(vector_x))) / (len(vector_x) - 1)

# Output the results
print(f"Vector X: {vector_x}")
print(f"Vector Y: {vector_y}")
print(f"Covariance: {covariance}")


Vector X: [1, 2, 3, 4, 5]
Vector Y: [5, 4, 3, 2, 1]
Covariance: -2.5


## Question 3 -
## Correlation between them.

In [ ]:
import numpy as np

# Define two 1xN dimensional arrays (N-dimensional feature vectors)
vector_x = np.array([1, 2, 3, 4, 5])
vector_y = np.array([10, 9, 2, 3, 1])

# Compute the covariance between the two vectors
covariance = np.cov(vector_x, vector_y)[0][1]

# Compute the standard deviations of both vectors
std_x = np.std(vector_x, ddof=1)
std_y = np.std(vector_y, ddof=1)

# Compute the correlation
correlation = covariance / (std_x * std_y)

# Output the results
print(f"Vector X: {vector_x}")
print(f"Vector Y: {vector_y}")
print(f"Correlation: {correlation}")


Vector X: [1 2 3 4 5]
Vector Y: [10  9  2  3  1]
Correlation: -0.9071147352221453


## Question 4 -
## Covariance matrix and Correlation matrix.


In [ ]:
import numpy as np

# Step 1: Create the Data Matrix
data = np.array([
    [2, 4, 6, 8, 10],
    [1, 3, 5, 7, 9],
    [10, 8, 6, 4, 2]
])

print("Data Matrix (3x5):")
print(data)

# Step 2: Compute the Covariance Matrix
cov_matrix = np.cov(data, bias=True)

print("\nCovariance Matrix (3x3):")
print(cov_matrix)

# Step 3: Compute the Correlation Matrix
corr_matrix = np.corrcoef(data)

print("\nCorrelation Matrix (3x3):")
print(corr_matrix)


Data Matrix (3x5):
[[ 2  4  6  8 10]
 [ 1  3  5  7  9]
 [10  8  6  4  2]]

Covariance Matrix (3x3):
[[ 8.  8. -8.]
 [ 8.  8. -8.]
 [-8. -8.  8.]]

Correlation Matrix (3x3):
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [-1. -1.  1.]]
